package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"gogql/graph/model"
)

// Description is the resolver for the description field.
func (r *climberResolver) Description(ctx context.Context, obj *model.Climber) (string, error) {
	if obj.Name == "Adam Ondra" {
		return "Goat", nil
	}

	return "", fmt.Errorf("Climber information not present")
}

// GetClimber is the resolver for the GetClimber field.
func (r *queryResolver) GetClimber(ctx context.Context, name string) (*model.Climber, error) {
	if name == "Adam Ondra" {
		age := int32(32)
		shoes := model.ShoesLasportiva
		return &model.Climber{Name: "Adam Ondra", Age: &age, Shoes: &shoes}, nil
	}

	return nil, fmt.Errorf("Climber Information not present")
}

// Climber returns ClimberResolver implementation.
func (r *Resolver) Climber() ClimberResolver { return &climberResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	climberResolver struct{ *Resolver }
	queryResolver   struct{ *Resolver }
)
