// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Climber struct {
	Name        string `json:"name"`
	Age         *int32 `json:"age,omitempty"`
	Shoes       *Shoes `json:"shoes,omitempty"`
	Description string `json:"description"`
}

type Query struct {
}

type Shoes string

const (
	ShoesLasportiva Shoes = "LASPORTIVA"
	ShoesScarpa     Shoes = "SCARPA"
	ShoesUnparallel Shoes = "UNPARALLEL"
)

var AllShoes = []Shoes{
	ShoesLasportiva,
	ShoesScarpa,
	ShoesUnparallel,
}

func (e Shoes) IsValid() bool {
	switch e {
	case ShoesLasportiva, ShoesScarpa, ShoesUnparallel:
		return true
	}
	return false
}

func (e Shoes) String() string {
	return string(e)
}

func (e *Shoes) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Shoes(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Shoes", str)
	}
	return nil
}

func (e Shoes) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Shoes) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Shoes) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
